/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Scanner;

public class App {

    public static boolean isStudyCat = false;

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
       
        System.out.println("Welcome to Study Cat!!!");
        System.out.println("Choose which study 'cat'egory you'd like to do today...");


        System.out.println("-----------------------------------------------------");
        /* 
        Database "Hero" display -
        Later make into list of terms list names (;"jlink list") & syntax flashcard decks (;"Java data structures").
        Just terms list for right now. 
        Also later add option to add new study cat (-> select study method (terms list, syntax flashcard, etc.) 
        -> cycle/method for inputting study cat name & answers -> displaying to review input study cat + confirmation). 
        */

        //Hero display : list of all study cats to choose from
        ArrayList<StudyCat> studyCats = new ArrayList<>();
        


        //adding list of all terms list study cats to Hero display model.
        ArrayDeque<TermsList> termsLists = DAL.showLists();
        for (TermsList list : termsLists) {
            studyCats.add(list);
        }


        //printing Hero display model
        for (StudyCat studyCat : studyCats) {
            System.out.println(studyCat.studyCatName);
        }

        System.out.println("-----------------------------------------------------");


        System.out.print("enter just the name, here: ");
        String catChoice = scanner.nextLine();
        System.out.println("you entered " + catChoice);

        StudyCat currentStudyCat = getCurrenStudyCat(studyCats, catChoice);
        

        if (isStudyCat) {
            System.out.println("That study cat exists.");

            System.out.println(currentStudyCat.id);
            //cycle for terms list study method chosen...
            TermsList.termsListStudyCatCycle(currentStudyCat, scanner);
        } else {
            System.out.println("study cat " + catChoice + " doesn't exist.");
        }


        scanner.close();
        System.out.println("Ending program.");
    }


    public static StudyCat getCurrenStudyCat(ArrayList<StudyCat> studyCats, String catChoice) {
        for (StudyCat studyCat : studyCats) {
            if (catChoice.strip().equalsIgnoreCase(studyCat.studyCatName)) {
                StudyCat currentStudyCat = new StudyCat(studyCat.id, studyCat.studyCatName, studyCat.Prompt);
                App.isStudyCat = true;
                return currentStudyCat;
            }
        }
        return null;
    }
}
