/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
       
        System.out.println("Welcome to Cat Study!!! ('cat'egory study)");
        System.out.println("Choose from the list of study methods below...");
        System.out.println();
    }
}
